version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: intellity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    restart: always
    container_name: minio_courserio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio-data: