"""empty message

Revision ID: bc59575ee5b6
Revises: e29324e64d33
Create Date: 2024-08-16 12:11:46.681252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc59575ee5b6'
down_revision: Union[str, None] = 'e29324e64d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chapter_model', 'title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_constraint('chapter_model_previous_chapter_id_fkey', 'chapter_model', type_='foreignkey')
    op.drop_column('chapter_model', 'previous_chapter_id')
    op.add_column('site_user_model', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('stage_model', sa.Column('sort_index', sa.Integer(), nullable=True))
    op.add_column('student_model', sa.Column('rate', sa.Integer(), nullable=True))
    op.add_column('teacher_model', sa.Column('rate', sa.Integer(), nullable=True))
    op.add_column('user_model', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'is_verified')
    op.drop_column('teacher_model', 'rate')
    op.drop_column('student_model', 'rate')
    op.drop_column('stage_model', 'sort_index')
    op.drop_column('site_user_model', 'is_superuser')
    op.add_column('chapter_model', sa.Column('previous_chapter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chapter_model_previous_chapter_id_fkey', 'chapter_model', 'chapter_model', ['previous_chapter_id'], ['id'])
    op.alter_column('chapter_model', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
