version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:123@<YOUR_SERVER_IP>:54321/intellity_db

    depends_on:
      - postgres

volumes:
  postgres_data:
    external: true