version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:123@intellitydb:5432/intellity_db
    depends_on:
      - intellitydb