version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:123@localhost:54321/intellity_db
    networks:
      - intellity_network

networks:
  intellity_network: