version: '3.8'

services:
  backend:
    build: .
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@80.78.243.39:5432/courserio_db
    networks:
      - courserio_network
    restart: unless-stopped

networks:
  courserio_network:
    external: true
