version: '3.8'

services:
  backend:
    build: .
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@79.174.94.29:5432/courserio_db
      - MINIO_URL=79.174.94.29:9000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-router.rule=Host(`backend.courserio.ru`)"
      - "traefik.http.routers.backend-router.entryPoints=websecure"
      - "traefik.http.routers.backend-router.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend-service.loadbalancer.server.port=8000"
    restart: unless-stopped
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
