version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@95.163.222.197:5432/intellity_db
    networks:
      - intellity_network

networks:
  intellity_network: