version: '3.8'

services:
  backend:
    build: .
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@79.174.94.29:5432/courserio_db
      - MINIO_URL=79.174.94.29:9000

    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - courserio_network

networks:
  courserio_network:
    external: true
