version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: courserio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gGHJDKSDK!UEssa09984!_KK
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - courserio_network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminUEssa09984!
    command: server /data --console-address ":9001"
    networks:
      - courserio_network

volumes:
  postgres_data:
  minio-data:

networks:
  courserio_network:
    external: true