version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: courserio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gGHJDKSDK!UEssa09984!_KK
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - courserio_network

volumes:
  postgres_data:

networks:
  courserio_network: