"""empty message

Revision ID: 08f07b030d17
Revises: 403049cb8caf
Create Date: 2024-03-25 00:27:42.560213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f07b030d17'
down_revision: Union[str, None] = '403049cb8caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_model', sa.Column('module_id', sa.Integer(), nullable=False))
    op.drop_constraint('stage_model_module_fkey', 'stage_model', type_='foreignkey')
    op.create_foreign_key(None, 'stage_model', 'module_model', ['module_id'], ['id'], ondelete='CASCADE')
    op.drop_column('stage_model', 'module')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_model', sa.Column('module', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stage_model', type_='foreignkey')
    op.create_foreign_key('stage_model_module_fkey', 'stage_model', 'module_model', ['module'], ['id'], ondelete='CASCADE')
    op.drop_column('stage_model', 'module_id')
    # ### end Alembic commands ###
