"""empty message

Revision ID: 0a09f247b530
Revises: e95141ab9a54
Create Date: 2024-08-13 13:48:12.016124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a09f247b530'
down_revision: Union[str, None] = 'e95141ab9a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_model', sa.Column('sort_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_model', 'sort_index')
    # ### end Alembic commands ###
