"""empty message

Revision ID: 134bd1787333
Revises: 0a09f247b530
Create Date: 2024-08-14 13:51:43.031895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '134bd1787333'
down_revision: Union[str, None] = '0a09f247b530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_progress', sa.Column('is_locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter_progress', 'is_locked')
    # ### end Alembic commands ###
