"""empty message

Revision ID: 17d9ee3e7a48
Revises: 5446635306c6
Create Date: 2024-03-23 12:59:49.490559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d9ee3e7a48'
down_revision: Union[str, None] = '5446635306c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chapter_model_title_key', 'chapter_model', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('chapter_model_title_key', 'chapter_model', ['title'])
    # ### end Alembic commands ###
