"""empty message

Revision ID: 197077db5d87
Revises: 
Create Date: 2024-06-09 10:22:25.401069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197077db5d87'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_category_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_course_category_model_id'), 'course_category_model', ['id'], unique=False)
    op.create_table('quiz_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_model_email'), 'user_model', ['email'], unique=True)
    op.create_index(op.f('ix_user_model_id'), 'user_model', ['id'], unique=False)
    op.create_table('student_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interested_categories', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('lastName', sa.String(length=64), nullable=True),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_views_counter', sa.BigInteger(), nullable=True),
    sa.Column('subscription_counter', sa.BigInteger(), nullable=True),
    sa.Column('cover_image_name', sa.String(), nullable=True),
    sa.Column('total_chapters', sa.BigInteger(), nullable=True),
    sa.Column('total_modules', sa.BigInteger(), nullable=True),
    sa.Column('total_stages', sa.BigInteger(), nullable=True),
    sa.Column('cover_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['course_category_model.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cover_path'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_course_model_cover_image_name'), 'course_model', ['cover_image_name'], unique=False)
    op.create_index(op.f('ix_course_model_id'), 'course_model', ['id'], unique=False)
    op.create_table('chapter_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=True),
    sa.Column('total_modules_in_chapter', sa.BigInteger(), nullable=True),
    sa.Column('total_stages_in_chapter', sa.BigInteger(), nullable=True),
    sa.Column('is_exam', sa.Boolean(), nullable=True),
    sa.Column('exam_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('previous_chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_chapter_id'], ['chapter_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_model_id'), 'chapter_model', ['id'], unique=False)
    op.create_table('course_enrollment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_model.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_enrollment_enrolled_time'), 'course_enrollment', ['enrolled_time'], unique=False)
    op.create_index(op.f('ix_course_enrollment_id'), 'course_enrollment', ['id'], unique=False)
    op.create_table('chapter_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter_model.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_progress_id'), 'chapter_progress', ['id'], unique=False)
    op.create_table('module_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_index', sa.Integer(), nullable=True),
    sa.Column('total_stages_in_module', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_model_id'), 'module_model', ['id'], unique=False)
    op.create_table('module_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module_model.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_progress_id'), 'module_progress', ['id'], unique=False)
    op.create_table('stage_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_model_id'), 'stage_model', ['id'], unique=False)
    op.create_table('stage_classic_lessons_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('html_code_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['stage_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_programming_lessons_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_string', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['stage_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage_model.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_progress_id'), 'stage_progress', ['id'], unique=False)
    op.create_table('stage_quiz_lessons_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_type_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['stage_model.id'], ),
    sa.ForeignKeyConstraint(['quiz_type_id'], ['quiz_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_video_lessons_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['stage_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_answers_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('is_true_answer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['stage_quiz_lessons_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_answers_model')
    op.drop_table('stage_video_lessons_model')
    op.drop_table('stage_quiz_lessons_model')
    op.drop_index(op.f('ix_stage_progress_id'), table_name='stage_progress')
    op.drop_table('stage_progress')
    op.drop_table('stage_programming_lessons_model')
    op.drop_table('stage_classic_lessons_model')
    op.drop_index(op.f('ix_stage_model_id'), table_name='stage_model')
    op.drop_table('stage_model')
    op.drop_index(op.f('ix_module_progress_id'), table_name='module_progress')
    op.drop_table('module_progress')
    op.drop_index(op.f('ix_module_model_id'), table_name='module_model')
    op.drop_table('module_model')
    op.drop_index(op.f('ix_chapter_progress_id'), table_name='chapter_progress')
    op.drop_table('chapter_progress')
    op.drop_index(op.f('ix_course_enrollment_id'), table_name='course_enrollment')
    op.drop_index(op.f('ix_course_enrollment_enrolled_time'), table_name='course_enrollment')
    op.drop_table('course_enrollment')
    op.drop_index(op.f('ix_chapter_model_id'), table_name='chapter_model')
    op.drop_table('chapter_model')
    op.drop_index(op.f('ix_course_model_id'), table_name='course_model')
    op.drop_index(op.f('ix_course_model_cover_image_name'), table_name='course_model')
    op.drop_table('course_model')
    op.drop_table('teacher_model')
    op.drop_table('student_model')
    op.drop_index(op.f('ix_user_model_id'), table_name='user_model')
    op.drop_index(op.f('ix_user_model_email'), table_name='user_model')
    op.drop_table('user_model')
    op.drop_table('quiz_types')
    op.drop_index(op.f('ix_course_category_model_id'), table_name='course_category_model')
    op.drop_table('course_category_model')
    # ### end Alembic commands ###
