"""empty message

Revision ID: 25eed1e3402b
Revises: bd0755ad4f17
Create Date: 2024-04-14 23:20:11.378974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25eed1e3402b'
down_revision: Union[str, None] = 'bd0755ad4f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_items', sa.Column('html_code_text', sa.String(), nullable=True))
    op.drop_column('stage_items', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_items', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('stage_items', 'html_code_text')
    # ### end Alembic commands ###
