"""empty message

Revision ID: 2f7d88050025
Revises: 9c9adb51dc9a
Create Date: 2024-06-20 12:02:35.964798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7d88050025'
down_revision: Union[str, None] = '9c9adb51dc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_model', sa.Column('solved_tasks_count', sa.Integer(), nullable=True))
    op.add_column('student_model', sa.Column('energy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_model', 'energy')
    op.drop_column('student_model', 'solved_tasks_count')
    # ### end Alembic commands ###
