"""add course status model

Revision ID: 3e5e0537a623
Revises: f81c4dddc90d
Create Date: 2024-06-09 19:19:50.868020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5e0537a623'
down_revision: Union[str, None] = 'f81c4dddc90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_status_model',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('status')
    )
    op.create_index(op.f('ix_course_status_model_id'), 'course_status_model', ['id'], unique=False)

    # Define the table for bulk_insert
    course_status_model = sa.Table(
        'course_status_model',
        sa.MetaData(),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('status', sa.String(), nullable=False),
    )

    # Insert default statuses
    op.bulk_insert(
        course_status_model,
        [
            {'id': 1, 'status': 'Draft'},
            {'id': 2, 'status': 'Published'},
            {'id': 3, 'status': 'Under Review'},
            {'id': 4, 'status': 'Archived'}
        ]
    )

    # Add the new column with a default value
    op.add_column('course_model', sa.Column('status_id', sa.Integer(), nullable=True, server_default='1'))

    # Update existing rows to have a default status
    op.execute('UPDATE course_model SET status_id = 1 WHERE status_id IS NULL')

    # Alter the column to be non-nullable
    op.alter_column('course_model', 'status_id', nullable=False, existing_type=sa.Integer)

    op.create_foreign_key(None, 'course_model', 'course_status_model', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_model', type_='foreignkey')
    op.drop_column('course_model', 'status_id')
    op.drop_index(op.f('ix_course_status_model_id'), table_name='course_status_model')
    op.drop_table('course_status_model')
    # ### end Alembic commands ###
