"""empty message

Revision ID: 403049cb8caf
Revises: 17d9ee3e7a48
Create Date: 2024-03-24 13:11:29.759847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403049cb8caf'
down_revision: Union[str, None] = '17d9ee3e7a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_model', sa.Column('chapter_id', sa.Integer(), nullable=False))
    op.drop_constraint('module_model_chapter_fkey', 'module_model', type_='foreignkey')
    op.create_foreign_key(None, 'module_model', 'chapter_model', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.drop_column('module_model', 'chapter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_model', sa.Column('chapter', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'module_model', type_='foreignkey')
    op.create_foreign_key('module_model_chapter_fkey', 'module_model', 'chapter_model', ['chapter'], ['id'], ondelete='CASCADE')
    op.drop_column('module_model', 'chapter_id')
    # ### end Alembic commands ###
