"""empty message

Revision ID: 49089bdc20bf
Revises: 25eed1e3402b
Create Date: 2024-04-21 13:32:53.842975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49089bdc20bf'
down_revision: Union[str, None] = '25eed1e3402b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_items', sa.Column('code_string', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_items', 'code_string')
    # ### end Alembic commands ###
