"""empty message

Revision ID: 5446635306c6
Revises: 80395eb5ad37
Create Date: 2024-03-23 10:58:22.139758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5446635306c6'
down_revision: Union[str, None] = '80395eb5ad37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_model', sa.Column('course_id', sa.Integer(), nullable=False))
    op.drop_constraint('chapter_model_course_fkey', 'chapter_model', type_='foreignkey')
    op.create_foreign_key(None, 'chapter_model', 'course_model', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chapter_model', 'course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_model', sa.Column('course', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chapter_model', type_='foreignkey')
    op.create_foreign_key('chapter_model_course_fkey', 'chapter_model', 'course_model', ['course'], ['id'], ondelete='CASCADE')
    op.drop_column('chapter_model', 'course_id')
    # ### end Alembic commands ###
