"""empty message

Revision ID: 5e64a904cb4a
Revises: 197077db5d87
Create Date: 2024-06-15 03:24:16.109263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e64a904cb4a'
down_revision: Union[str, None] = '197077db5d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_moderation_status_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_index(op.f('ix_course_moderation_status_model_id'), 'course_moderation_status_model', ['id'], unique=False)
    op.create_table('course_status_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.create_index(op.f('ix_course_status_model_id'), 'course_status_model', ['id'], unique=False)
    op.alter_column('chapter_progress', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('course_model', sa.Column('status_id', sa.Integer(), nullable=False))
    op.add_column('course_model', sa.Column('moderation_status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_model', 'course_status_model', ['status_id'], ['id'])
    op.create_foreign_key(None, 'course_model', 'course_moderation_status_model', ['moderation_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_model', type_='foreignkey')
    op.drop_constraint(None, 'course_model', type_='foreignkey')
    op.drop_column('course_model', 'moderation_status_id')
    op.drop_column('course_model', 'status_id')
    op.alter_column('chapter_progress', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_course_status_model_id'), table_name='course_status_model')
    op.drop_table('course_status_model')
    op.drop_index(op.f('ix_course_moderation_status_model_id'), table_name='course_moderation_status_model')
    op.drop_table('course_moderation_status_model')
    # ### end Alembic commands ###
