"""empty message

Revision ID: 6274d86a4e4b
Revises: 87a88a7c80a6
Create Date: 2024-08-02 10:51:43.669484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6274d86a4e4b'
down_revision: Union[str, None] = '87a88a7c80a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_action'), 'action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_action_logs_id'), 'action_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_logs_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_action'), table_name='action_logs')
    op.drop_table('action_logs')
    # ### end Alembic commands ###
