"""empty message

Revision ID: 6e8413512528
Revises: 2f7d88050025
Create Date: 2024-07-02 22:19:24.208585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8413512528'
down_revision: Union[str, None] = '2f7d88050025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chapter_model_previous_chapter_id_fkey', 'chapter_model', type_='foreignkey')
    op.drop_column('chapter_model', 'previous_chapter_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_model', sa.Column('previous_chapter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chapter_model_previous_chapter_id_fkey', 'chapter_model', 'chapter_model', ['previous_chapter_id'], ['id'])
    # ### end Alembic commands ###
