"""empty message

Revision ID: 80395eb5ad37
Revises: 4bb28cd02d3e
Create Date: 2024-03-21 23:55:13.473215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80395eb5ad37'
down_revision: Union[str, None] = '4bb28cd02d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('module', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module'], ['module_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_model_id'), 'stage_model', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_model_id'), table_name='stage_model')
    op.drop_table('stage_model')
    # ### end Alembic commands ###
