"""empty message

Revision ID: 88ac9ce40fa4
Revises: da499d4a057b
Create Date: 2024-05-21 17:27:10.555462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ac9ce40fa4'
down_revision: Union[str, None] = 'da499d4a057b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_model', sa.Column('course_views_counter', sa.BigInteger(), nullable=True))
    op.add_column('course_model', sa.Column('subscription_counter', sa.BigInteger(), nullable=True))
    op.drop_column('course_model', 'course_views')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_model', sa.Column('course_views', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('course_model', 'subscription_counter')
    op.drop_column('course_model', 'course_views_counter')
    # ### end Alembic commands ###
