"""empty message

Revision ID: 88db391261be
Revises: 2f93e5ddbb8f
Create Date: 2024-05-13 19:46:39.840338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88db391261be'
down_revision: Union[str, None] = '2f93e5ddbb8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_model', sa.Column('sorted', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter_model', 'sorted')
    # ### end Alembic commands ###
