"""empty message

Revision ID: 897a9dc3b84c
Revises: 467afe637409
Create Date: 2024-05-01 20:43:38.714936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '897a9dc3b84c'
down_revision: Union[str, None] = '467afe637409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions_questions', sa.Column('quiz_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions_questions', 'stage_model', ['quiz_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions_questions', type_='foreignkey')
    op.drop_column('questions_questions', 'quiz_id')
    # ### end Alembic commands ###
