"""empty message

Revision ID: 898fdbd3006f
Revises: a008cc6bed3e
Create Date: 2024-06-14 00:09:03.994426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '898fdbd3006f'
down_revision: Union[str, None] = 'a008cc6bed3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter_model.id'], name='exam_progress_chapter_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['student_model.id'], name='exam_progress_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exam_progress_pkey')
    )
    # ### end Alembic commands ###
