"""empty message

Revision ID: 89aa5c7ae544
Revises: 583a7fd1e299
Create Date: 2024-04-23 22:43:43.048891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89aa5c7ae544'
down_revision: Union[str, None] = '583a7fd1e299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_model', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('teacher_model', sa.Column('lastName', sa.String(length=64), nullable=True))
    op.drop_index('ix_user_model_name', table_name='user_model')
    op.drop_column('user_model', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_user_model_name', 'user_model', ['name'], unique=True)
    op.drop_column('teacher_model', 'lastName')
    op.drop_column('teacher_model', 'name')
    # ### end Alembic commands ###
