"""empty message

Revision ID: 8d905349e5c8
Revises: decb869ccb3f
Create Date: 2024-03-25 00:37:54.247708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d905349e5c8'
down_revision: Union[str, None] = 'decb869ccb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_items', sa.Column('stage_id', sa.Integer(), nullable=True))
    op.add_column('stage_items', sa.Column('text', sa.String(), nullable=True))
    op.create_foreign_key(None, 'stage_items', 'stage_model', ['stage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stage_items', type_='foreignkey')
    op.drop_column('stage_items', 'text')
    op.drop_column('stage_items', 'stage_id')
    # ### end Alembic commands ###
