"""empty message

Revision ID: 959c7af456fc
Revises: 3ce3b31be7eb
Create Date: 2024-06-19 15:34:21.654236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959c7af456fc'
down_revision: Union[str, None] = '3ce3b31be7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blog_model_title_key', 'blog_model', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('blog_model_title_key', 'blog_model', ['title'])
    # ### end Alembic commands ###
