"""empty message

Revision ID: 99fd8a8d9957
Revises: 134bd1787333
Create Date: 2024-08-14 14:03:57.680981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99fd8a8d9957'
down_revision: Union[str, None] = '134bd1787333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter_progress', 'is_locked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_progress', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
