"""empty message

Revision ID: 9b603aba235d
Revises: 
Create Date: 2024-05-01 20:34:05.086313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b603aba235d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_category_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_course_category_model_id'), 'course_category_model', ['id'], unique=False)
    op.create_table('questions_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_true_answer', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_model_email'), 'user_model', ['email'], unique=True)
    op.create_index(op.f('ix_user_model_id'), 'user_model', ['id'], unique=False)
    op.create_table('student_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interested_categories', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('lastName', sa.String(length=64), nullable=True),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('course_views', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['course_category_model.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_course_model_id'), 'course_model', ['id'], unique=False)
    op.create_table('chapter_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_model_id'), 'chapter_model', ['id'], unique=False)
    op.create_table('module_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_model_id'), 'module_model', ['id'], unique=False)
    op.create_table('stage_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('html_code_text', sa.String(), nullable=True),
    sa.Column('video_link', sa.String(), nullable=True),
    sa.Column('code_string', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_model_id'), 'stage_model', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_model_id'), table_name='stage_model')
    op.drop_table('stage_model')
    op.drop_index(op.f('ix_module_model_id'), table_name='module_model')
    op.drop_table('module_model')
    op.drop_index(op.f('ix_chapter_model_id'), table_name='chapter_model')
    op.drop_table('chapter_model')
    op.drop_index(op.f('ix_course_model_id'), table_name='course_model')
    op.drop_table('course_model')
    op.drop_table('teacher_model')
    op.drop_table('student_model')
    op.drop_index(op.f('ix_user_model_id'), table_name='user_model')
    op.drop_index(op.f('ix_user_model_email'), table_name='user_model')
    op.drop_table('user_model')
    op.drop_table('questions_questions')
    op.drop_index(op.f('ix_course_category_model_id'), table_name='course_category_model')
    op.drop_table('course_category_model')
    # ### end Alembic commands ###
