"""empty message

Revision ID: 9bcb4ffb2909
Revises: e30b5a5f25ad
Create Date: 2024-03-21 21:40:36.118458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bcb4ffb2909'
down_revision: Union[str, None] = 'e30b5a5f25ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('course_views', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['course_category_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_course_model_id'), 'course_model', ['id'], unique=False)
    op.alter_column('course_category_model', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('course_category_model', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_category_model', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('course_category_model', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_course_model_id'), table_name='course_model')
    op.drop_table('course_model')
    # ### end Alembic commands ###
