"""empty message

Revision ID: 9c7985f435da
Revises: 3923788845c5
Create Date: 2024-04-13 23:44:46.906325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7985f435da'
down_revision: Union[str, None] = '3923788845c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_items', sa.Column('video_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_items', 'video_link')
    # ### end Alembic commands ###
