"""empty message

Revision ID: 9c9adb51dc9a
Revises: f07aebd4c18b
Create Date: 2024-06-20 11:58:52.189490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9adb51dc9a'
down_revision: Union[str, None] = 'f07aebd4c18b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blog_model_owner_id_fkey', 'blog_model', type_='foreignkey')
    op.create_foreign_key(None, 'blog_model', 'user_model', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_model', type_='foreignkey')
    op.create_foreign_key('blog_model_owner_id_fkey', 'blog_model', 'teacher_model', ['owner_id'], ['id'])
    # ### end Alembic commands ###
