"""empty message

Revision ID: 9e60b3834f06
Revises: 880ba2800da3
Create Date: 2024-08-23 12:11:31.710452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e60b3834f06'
down_revision: Union[str, None] = '880ba2800da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_types_id'), 'log_types', ['id'], unique=False)
    op.create_index(op.f('ix_log_types_name'), 'log_types', ['name'], unique=True)
    op.create_table('action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('log_type_id', sa.Integer(), nullable=True),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['log_type_id'], ['log_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_logs_action'), 'action_logs', ['action'], unique=False)
    op.create_index(op.f('ix_action_logs_id'), 'action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_action_logs_model_name'), 'action_logs', ['model_name'], unique=False)
    op.create_index(op.f('ix_action_logs_object_id'), 'action_logs', ['object_id'], unique=False)
    op.alter_column('blog_category_model', 'title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_category_model', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.drop_index(op.f('ix_action_logs_object_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_model_name'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_action'), table_name='action_logs')
    op.drop_table('action_logs')
    op.drop_index(op.f('ix_log_types_name'), table_name='log_types')
    op.drop_index(op.f('ix_log_types_id'), table_name='log_types')
    op.drop_table('log_types')
    # ### end Alembic commands ###
