"""empty message

Revision ID: a0b2d7360a7d
Revises: a4a2066a3d99
Create Date: 2024-05-14 15:48:08.927127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b2d7360a7d'
down_revision: Union[str, None] = 'a4a2066a3d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_model', sa.Column('sort_index', sa.Integer(), nullable=False))
    op.drop_column('chapter_model', 'sorted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_model', sa.Column('sorted', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('chapter_model', 'sort_index')
    # ### end Alembic commands ###
