"""empty message

Revision ID: a6c57413a343
Revises: 
Create Date: 2024-07-31 21:54:32.301164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c57413a343'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_model', sa.Column('previous_chapter_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chapter_model', 'chapter_model', ['previous_chapter_id'], ['id'])
    op.add_column('site_user_model', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('student_model', sa.Column('rate', sa.Integer(), nullable=True))
    op.add_column('teacher_model', sa.Column('rate', sa.Integer(), nullable=True))
    op.add_column('user_model', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'is_verified')
    op.drop_column('teacher_model', 'rate')
    op.drop_column('student_model', 'rate')
    op.drop_column('site_user_model', 'is_superuser')
    op.drop_constraint(None, 'chapter_model', type_='foreignkey')
    op.drop_column('chapter_model', 'previous_chapter_id')
    # ### end Alembic commands ###
