"""empty message

Revision ID: adde276d2de9
Revises: c42dc77b9686
Create Date: 2024-05-31 14:47:21.789974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adde276d2de9'
down_revision: Union[str, None] = 'c42dc77b9686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_questions_model', 'question_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('quiz_questions_model', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quiz_questions_model', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('quiz_questions_model', 'is_true_answer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_questions_model', 'is_true_answer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('quiz_questions_model', 'quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quiz_questions_model', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quiz_questions_model', 'question_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
