"""empty message

Revision ID: b51d76045f36
Revises: ebe1a7fa9da6
Create Date: 2024-05-16 18:09:08.151374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51d76045f36'
down_revision: Union[str, None] = 'ebe1a7fa9da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_model', sa.Column('is_exam', sa.Boolean(), nullable=False))
    op.add_column('chapter_model', sa.Column('exam_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter_model', 'exam_duration_minutes')
    op.drop_column('chapter_model', 'is_exam')
    # ### end Alembic commands ###
