"""empty message

Revision ID: b60897b836d8
Revises: 959c7af456fc
Create Date: 2024-06-19 19:45:08.860452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60897b836d8'
down_revision: Union[str, None] = '959c7af456fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_model', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('blog_model', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_model', 'updated_at')
    op.drop_column('blog_model', 'created_at')
    # ### end Alembic commands ###
