"""empty message

Revision ID: bd0755ad4f17
Revises: 6909e68a3d35
Create Date: 2024-04-14 10:56:47.451112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0755ad4f17'
down_revision: Union[str, None] = '6909e68a3d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions_questions', sa.Column('question_text', sa.String(), nullable=True))
    op.add_column('questions_questions', sa.Column('is_true_answer', sa.Boolean(), nullable=True))
    op.drop_column('questions_questions', 'text')
    op.drop_column('questions_questions', 'correct_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions_questions', sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('questions_questions', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('questions_questions', 'is_true_answer')
    op.drop_column('questions_questions', 'question_text')
    # ### end Alembic commands ###
