"""empty message

Revision ID: bef01d778305
Revises: 9e60b3834f06
Create Date: 2024-08-25 20:20:57.032604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef01d778305'
down_revision: Union[str, None] = '9e60b3834f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_enrollment', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_enrollment', 'is_active')
    # ### end Alembic commands ###
