"""empty message

Revision ID: bf0d88bf9694
Revises: d23de202e537
Create Date: 2024-05-30 21:46:39.704179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0d88bf9694'
down_revision: Union[str, None] = 'd23de202e537'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.add_column('stage_model', sa.Column('quiz_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stage_model', 'quiz_types', ['quiz_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stage_model', type_='foreignkey')
    op.drop_column('stage_model', 'quiz_type_id')
    op.drop_table('quiz_types')
    # ### end Alembic commands ###
