"""empty message

Revision ID: c33badbebccd
Revises: 9bcb4ffb2909
Create Date: 2024-03-21 22:24:47.738460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c33badbebccd'
down_revision: Union[str, None] = '9bcb4ffb2909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['course'], ['course_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_chapter_model_id'), 'chapter_model', ['id'], unique=False)
    op.create_table('module_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chapter'], ['chapter_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_model_id'), 'module_model', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_module_model_id'), table_name='module_model')
    op.drop_table('module_model')
    op.drop_index(op.f('ix_chapter_model_id'), table_name='chapter_model')
    op.drop_table('chapter_model')
    # ### end Alembic commands ###
