"""empty message

Revision ID: ca699a9d0f17
Revises: 5e64a904cb4a
Create Date: 2024-06-20 12:10:36.658421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca699a9d0f17'
down_revision: Union[str, None] = '5e64a904cb4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privilege_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_privilege_model_id'), 'privilege_model', ['id'], unique=False)
    op.create_table('role_model',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_role_model_id'), 'role_model', ['id'], unique=False)
    op.create_table('role_privilege_association',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('privilege_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['privilege_id'], ['privilege_model.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role_model.id'], )
    )
    op.create_table('site_user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user_model.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('student_model', sa.Column('solved_tasks_count', sa.Integer(), nullable=True))
    op.add_column('student_model', sa.Column('energy', sa.Integer(), nullable=True))
    op.add_column('user_model', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'is_active')
    op.drop_column('student_model', 'energy')
    op.drop_column('student_model', 'solved_tasks_count')
    op.drop_table('site_user_model')
    op.drop_table('role_privilege_association')
    op.drop_index(op.f('ix_role_model_id'), table_name='role_model')
    op.drop_table('role_model')
    op.drop_index(op.f('ix_privilege_model_id'), table_name='privilege_model')
    op.drop_table('privilege_model')
    # ### end Alembic commands ###
