"""empty message

Revision ID: d680976d29da
Revises: e8f6e451e4c7
Create Date: 2024-05-31 17:45:09.848187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd680976d29da'
down_revision: Union[str, None] = 'e8f6e451e4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_quiz_lessons_model', sa.Column('question', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_quiz_lessons_model', 'question')
    # ### end Alembic commands ###
