"""empty message

Revision ID: d69b589292ba
Revises: f5df9ed39bfa
Create Date: 2024-07-30 11:38:11.985149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69b589292ba'
down_revision: Union[str, None] = 'f5df9ed39bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_user_model', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('user_model', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'is_verified')
    op.drop_column('site_user_model', 'is_superuser')
    # ### end Alembic commands ###
