"""empty message

Revision ID: da499d4a057b
Revises: d1f23c8b3192
Create Date: 2024-05-20 15:44:56.854196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da499d4a057b'
down_revision: Union[str, None] = 'd1f23c8b3192'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_enrollment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course_model.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_enrollment_enrolled_time'), 'course_enrollment', ['enrolled_time'], unique=False)
    op.create_index(op.f('ix_course_enrollment_id'), 'course_enrollment', ['id'], unique=False)
    op.create_table('chapter_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter_model.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_progress_id'), 'chapter_progress', ['id'], unique=False)
    op.create_table('module_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module_model.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_progress_id'), 'module_progress', ['id'], unique=False)
    op.create_table('stage_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage_model.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_progress_id'), 'stage_progress', ['id'], unique=False)
    op.alter_column('chapter_model', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chapter_model', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('chapter_model', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chapter_model', 'sort_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chapter_model', 'is_exam',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('course_category_model', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('course_category_model', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('course_model', 'category',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('course_model', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('course_model', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('course_model', 'course_views',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('module_model', 'chapter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('module_model', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('module_model', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('module_model', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('module_model', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('module_model', 'chapter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course_model', 'course_views',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('course_model', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('course_model', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('course_model', 'category',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('course_category_model', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('course_category_model', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('chapter_model', 'is_exam',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('chapter_model', 'sort_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('chapter_model', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chapter_model', 'title',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('chapter_model', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_stage_progress_id'), table_name='stage_progress')
    op.drop_table('stage_progress')
    op.drop_index(op.f('ix_module_progress_id'), table_name='module_progress')
    op.drop_table('module_progress')
    op.drop_index(op.f('ix_chapter_progress_id'), table_name='chapter_progress')
    op.drop_table('chapter_progress')
    op.drop_index(op.f('ix_course_enrollment_id'), table_name='course_enrollment')
    op.drop_index(op.f('ix_course_enrollment_enrolled_time'), table_name='course_enrollment')
    op.drop_table('course_enrollment')
    # ### end Alembic commands ###
