"""empty message

Revision ID: daee54de6d89
Revises: 19dd7008bbb0
Create Date: 2024-04-07 20:12:29.088933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daee54de6d89'
down_revision: Union[str, None] = '19dd7008bbb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_model', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_model', 'teacher_model', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_model', type_='foreignkey')
    op.drop_column('course_model', 'teacher_id')
    # ### end Alembic commands ###
