"""empty message

Revision ID: e8f6e451e4c7
Revises: adde276d2de9
Create Date: 2024-05-31 17:35:00.944710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f6e451e4c7'
down_revision: Union[str, None] = 'adde276d2de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_answers_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('is_true_answer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['stage_quiz_lessons_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quiz_questions_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_questions_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_true_answer', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['stage_quiz_lessons_model.id'], name='quiz_questions_model_quiz_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='quiz_questions_model_pkey')
    )
    op.drop_table('quiz_answers_model')
    # ### end Alembic commands ###
