"""empty message

Revision ID: e95141ab9a54
Revises: 434ba63d0c2c
Create Date: 2024-08-05 15:28:17.965386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e95141ab9a54'
down_revision: Union[str, None] = '434ba63d0c2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chapter_model', 'title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               nullable=False)
    op.drop_constraint('chapter_model_previous_chapter_id_fkey', 'chapter_model', type_='foreignkey')
    op.drop_column('chapter_model', 'previous_chapter_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_model', sa.Column('previous_chapter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chapter_model_previous_chapter_id_fkey', 'chapter_model', 'chapter_model', ['previous_chapter_id'], ['id'])
    op.alter_column('chapter_model', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
