"""empty message

Revision ID: ebe1a7fa9da6
Revises: f1dd0af5922d
Create Date: 2024-05-16 14:19:29.417395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe1a7fa9da6'
down_revision: Union[str, None] = 'f1dd0af5922d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_model', 'descriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_model', sa.Column('descriptions', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
