"""empty message

Revision ID: f07aebd4c18b
Revises: df413416b516
Create Date: 2024-06-19 22:01:16.052813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07aebd4c18b'
down_revision: Union[str, None] = 'df413416b516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_role_association')
    op.add_column('site_user_model', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'site_user_model', 'role_model', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'site_user_model', type_='foreignkey')
    op.drop_column('site_user_model', 'role_id')
    op.create_table('admin_role_association',
    sa.Column('site_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role_model.id'], name='admin_role_association_role_id_fkey'),
    sa.ForeignKeyConstraint(['site_user_id'], ['site_user_model.id'], name='admin_role_association_site_user_id_fkey')
    )
    # ### end Alembic commands ###
