"""empty message

Revision ID: f1dd0af5922d
Revises: a0b2d7360a7d
Create Date: 2024-05-16 11:07:39.168232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1dd0af5922d'
down_revision: Union[str, None] = 'a0b2d7360a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_model', sa.Column('descriptions', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_model', 'descriptions')
    # ### end Alembic commands ###
