"""empty message

Revision ID: f5df9ed39bfa
Revises: 2f7d88050025
Create Date: 2024-07-30 11:21:36.754225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5df9ed39bfa'
down_revision: Union[str, None] = '2f7d88050025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_model', sa.Column('rate', sa.Integer(), nullable=True))
    op.add_column('teacher_model', sa.Column('rate', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_model', 'rate')
    op.drop_column('student_model', 'rate')
    # ### end Alembic commands ###
