"""empty message

Revision ID: f81c4dddc90d
Revises: 4736bdff0c71
Create Date: 2024-06-04 00:53:52.900217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81c4dddc90d'
down_revision: Union[str, None] = '4736bdff0c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_model', sa.Column('sort_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_model', 'sort_index')
    # ### end Alembic commands ###
