"""empty message

Revision ID: fa5b3eae0c0b
Revises: 163287492934
Create Date: 2024-09-25 16:06:57.724036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa5b3eae0c0b'
down_revision: Union[str, None] = '163287492934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter_progress', sa.Column('is_locked', sa.Boolean(), nullable=False))
    op.drop_column('stage_progress', 'is_locked')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stage_progress', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('chapter_progress', 'is_locked')
    # ### end Alembic commands ###
