version: '3.8'

services:
  postgres:
    build: .
    container_name: my_postgres
    environment:
      POSTGRES_DB: intellity_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dfvbd3246354**&%$!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  pgdata:

networks:
  postgres_network:
    driver: bridge