# Используем официальный образ PostgreSQL
FROM postgres:16

# Устанавливаем переменные окружения
ENV POSTGRES_DB=intellity_db
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=dfvbd3246354**&%$!

# Копируем SQL файл с инициализацией базы данных (опционально)
# COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432